- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    key_name: "omartsyniuk@okhamer-Latitude"
    region: eu-central-1
    instance_type: t2.micro
    image: "ami-97e953f8"
    security_group: "sg-7b3d1d13"

  tasks:
  - name: Provision an instance
    ec2:
      key_name: "{{ key_name }}"
      instance_type: "{{ instance_type }}"
      image: "{{ image }}"
      region: "{{ region }}"
      group_id: "{{ security_group }}"
      #assign_public_ip: yes
      wait: true
      exact_count: 1
      count_tag:
        name: Test2
      instance_tags:
        name: Test2
    register: ec2

  - name: Add new instances IPs to host group
    add_host:
      hostname: "{{ item.public_ip }}"
      groupname: launched
    with_items: "{{ ec2.instances }}"

  - name: Wait for SSH to come up
    wait_for:
      host: "{{ item.public_dns_name }}"
      port: 22
      delay: 60
      timeout: 320
      state: started
    with_items: "{{ ec2.instances }}"

- name: Configure instance(s)
  hosts: launched
  become: true
  user: ubuntu
  gather_facts: false
  pre_tasks:
    - name: Install python for Ansible
      raw: bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qqy python-minimal)"
      register: output
      changed_when: output.stdout != ""
    - name: Gathering Facts
      setup:

  #tasks:
  #  - name: Check NTP service
  #    service: name=ntpd state=started

#    - name: Terminate instances
#      hosts: localhost
#      connection: local
#      tasks:
#        - name: Terminate instances that were previously launched
#          ec2:
#            state: 'absent'
#            instance_ids: '{{ ec2.instance_ids }}'
